/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations, useTexture } from "@react-three/drei";
import url from "/public/box.png"
import * as THREE from 'three'
export function Room4(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/roomBuzon2.glb");
  const { actions } = useAnimations(animations, group);
  const texture = useTexture(url)

  useEffect(()=>{
    actions.Armature.play()
    console.log("actions room4",actions)
  })
  return (
    <group ref={group} {...props} dispose={null}   position={[-57,-15,-17]}  rotation={[0,Math.PI/-4,0]}>
      <group name="Scene">
        <group
          name="Armature"
          position={[8.82, 16.04, 0.96]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={3.24}
          frustumCulled={false}
        >
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="Brow"
            geometry={nodes.Brow.geometry}
            material={materials["Material.065"]}
            skeleton={nodes.Brow.skeleton}
            frustumCulled={false}
          />
          <skinnedMesh
            name="Clock"
            geometry={nodes.Clock.geometry}
            material={materials["Material.064"]}
            skeleton={nodes.Clock.skeleton}
            frustumCulled={false}
          />
          <skinnedMesh
            name="Eyes"
            geometry={nodes.Eyes.geometry}
            material={materials["Material.063"]}
            skeleton={nodes.Eyes.skeleton}
            frustumCulled={false}
          />
          <skinnedMesh
            name="Pants"
            geometry={nodes.Pants.geometry}
            material={materials["Material.059"]}
            skeleton={nodes.Pants.skeleton}
            frustumCulled={false}
          />
          <skinnedMesh
            name="Hair"
            geometry={nodes.Hair.geometry}
            material={materials["Material.062"]}
            skeleton={nodes.Hair.skeleton}
            frustumCulled={false}
          />
          <skinnedMesh
            name="Hat"
            geometry={nodes.Hat.geometry}
            material={materials["Material.061"]}
            skeleton={nodes.Hat.skeleton}
            frustumCulled={false}
          />
          <skinnedMesh
            name="Hat_Icon"
            geometry={nodes.Hat_Icon.geometry}
            material={materials["Material.060"]}
            skeleton={nodes.Hat_Icon.skeleton}
            frustumCulled={false}
          />
          <skinnedMesh
            name="ShoesR"
            geometry={nodes.ShoesR.geometry}
            material={materials.zapatos}
            skeleton={nodes.ShoesR.skeleton}
            material-color={"#3b83bd"}
            frustumCulled={false}
          />
          <skinnedMesh
            name="Tshirt_art"
            geometry={nodes.Tshirt_art.geometry}
            material={materials["Material.057"]}
            skeleton={nodes.Tshirt_art.skeleton}
            frustumCulled={false}
          />
          <group name="Body">
            <skinnedMesh
              name="Circle010"
              geometry={nodes.Circle010.geometry}
              material={materials["Material.066"]}
              skeleton={nodes.Circle010.skeleton}
              frustumCulled={false}
            />
            <skinnedMesh
              name="Circle010_1"
              geometry={nodes.Circle010_1.geometry}
              material={materials["Material.067"]}
              skeleton={nodes.Circle010_1.skeleton}
              frustumCulled={false}
            />
            <skinnedMesh
              name="Circle010_2"
              geometry={nodes.Circle010_2.geometry}
              material={materials["Material.068"]}
              skeleton={nodes.Circle010_2.skeleton}
              frustumCulled={false}
            />
          </group>
          <skinnedMesh
            name="Tshirt"
            geometry={nodes.Tshirt.geometry}
            material={materials["Material.058"]}
            skeleton={nodes.Tshirt.skeleton}
            frustumCulled={false}
          />
          <skinnedMesh
            name="ShoeL"
            geometry={nodes.ShoeL.geometry}
            material={materials.zapatos}
            skeleton={nodes.ShoeL.skeleton}
            frustumCulled={false}
          />
        </group>
        <mesh
          name="Cube"
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials["Material.035"]}
          position={[4.64, 15.62, 2.79]}
          scale={[0.84, 0.02, 0.56]}
        />
        <mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials.cubierta}
          position={[4.64, 15.27, 2.79]}
        />
        <mesh
          name="Cube002"
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials.cubierta}
          position={[4.82, 15.62, 2.28]}
          rotation={[0, -0.39, 0]}
          scale={[0.43, 0.01, 0.64]}
        />
        <group
          name="carta"
          position={[11.29, 15.27, 3.59]}
          rotation={[0, 0.84, 0]}
        >
          <mesh
            name="Plane012"
            castShadow
            receiveShadow
            geometry={nodes.Plane012.geometry}
            material={materials.cubierta}
          />
          <mesh
            name="Plane012_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane012_1.geometry}
            material={materials["Material.035"]}
          />
        </group>
        <group
          name="carta002"
          position={[7.77, 17.46, -5.36]}
          rotation={[0, -1.14, 0]}
          scale={0.72}
        >
          <mesh
            name="Plane018"
            castShadow
            receiveShadow
            geometry={nodes.Plane018.geometry}
            material={materials.cubierta}
          />
          <mesh
            name="Plane018_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane018_1.geometry}
            material={materials["Material.035"]}
          />
        </group>
        <group
          name="carta001"
          position={[8.15, 16.41, -3.98]}
          rotation={[0, 0.84, 0]}
          scale={0.72}
        >
          <mesh
            name="Plane013"
            castShadow
            receiveShadow
            geometry={nodes.Plane013.geometry}
            material={materials.cubierta}
          />
          <mesh
            name="Plane013_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane013_1.geometry}
            material={materials["Material.035"]}
          />
        </group>
        <group name="carta003" position={[1.92, 15.26, -4.26]}>
          <mesh
            name="Plane019"
            castShadow
            receiveShadow
            geometry={nodes.Plane019.geometry}
            material={materials.cubierta}
          />
          <mesh
            name="Plane019_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane019_1.geometry}
            material={materials["Material.035"]}
          />
        </group>
        <group
          name="carta004"
          position={[0.6, 16.45, -2.19]}
          rotation={[0, 0.84, 0]}
          scale={0.58}
        >
          <mesh
            name="Plane020"
            castShadow
            receiveShadow
            geometry={nodes.Plane020.geometry}
            material={materials.cubierta}
          />
          <mesh
            name="Plane020_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane020_1.geometry}
            material={materials["Material.035"]}
          />
        </group>
        <group
          name="carta005"
          position={[0.85, 16.45, -2.19]}
          rotation={[-Math.PI, 1.28, -Math.PI]}
          scale={0.58}
        >
          <mesh
            name="Plane021"
            castShadow
            receiveShadow
            geometry={nodes.Plane021.geometry}
            material={materials.cubierta}
          />
          <mesh
            name="Plane021_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane021_1.geometry}
            material={materials["Material.035"]}
            material-color={"#8d8894"} 
          />
        </group>
        <mesh
          name="pared"
          castShadow
          receiveShadow
          geometry={nodes.pared.geometry}
          material={materials["Material.069"]}
          position={[-15.46, 44.57, 18.81]}
          rotation={[0,Math.PI/4.5,0]}
          scale={-28.99}
        />
        <mesh
          name="box_00"
          castShadow
          receiveShadow
          geometry={nodes.box_00.geometry}
          material={new THREE.MeshPhysicalMaterial({
            map: texture,
                    })}
          position={[0, 15.55, -8.94]}
          scale={[0.03, 0.02, 0.03]}
        />
        <mesh
          name="box_00001"
          castShadow
          receiveShadow
          geometry={nodes.box_00001.geometry}
          material={new THREE.MeshPhysicalMaterial({
            map: texture,
                    })}
          position={[-1.75, 17.6, -5.38]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.02}
        />
        <mesh
          name="box_00002"
          castShadow
          receiveShadow
          geometry={nodes.box_00002.geometry}
          material={new THREE.MeshPhysicalMaterial({
            map: texture,
                    })}
          position={[5.78, 15.63, -5.38]}
          rotation={[-Math.PI, 1.15, -Math.PI]}
          scale={0.02}
        />
        <mesh
          name="box_00003"
          castShadow
          receiveShadow
          geometry={nodes.box_00003.geometry}
          material={new THREE.MeshPhysicalMaterial({
            map: texture,
                    })}
          position={[8.89, 15.63, -3.11]}
          rotation={[Math.PI, -0.43, Math.PI]}
          scale={0.01}
        />
        <mesh
          name="box_00004"
          castShadow
          receiveShadow
          geometry={nodes.box_00004.geometry}
          material={new THREE.MeshPhysicalMaterial({
            map: texture,
                    })}
          position={[1.46, 15.63, -1.39]}
          rotation={[Math.PI, -0.59, Math.PI]}
          scale={0.01}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/roomBuzon2.glb");
